baseURL = "http://ii.pw.edu.pl/"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "researcher"
languageCode = 'en-us'
title="Kamil Żbikowski"

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en'
    languageFlag = "🇬🇧"
    languageName = 'English'
    weight = 0

  [languages.pl]
    contentDir = 'content/pl'
    languageCode = 'pl'
    languageFlag = "🇵🇱"
    languageName = 'Polski'
    weight = 1

disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Kamil Żbikowski"
  description = "A simple monospaced resume theme for Hugo."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "Theme By Olivier Roques"
    url = "https://github.com/ojroques/hugo-researcher"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:kamil.zbikowski@pw.edu.pl"

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files



[menu]
  [[menu.main]]
    identifier = "home"
    url = "/about"
    weight = 1
  [[menu.main]]
    identifier = "contact"
    url = "/contact"
    weight = 2